#!/usr/bin/env bash
# Run a command inside the spun-up VM
set -Eeuo pipefail

command -v ssh >/dev/null

SSH_PORT=${SSH_PORT:-2234}

exec ssh -i "$(dirname "$0")/tmp/ssh-key" -p "$SSH_PORT" \
         -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
         root@127.0.0.1 "$@"
