#!/usr/bin/env bash
# Run a command inside the spun-up VM
set -Eeuo pipefail

command -v ssh >/dev/null

SSHPORT=${SSHPORT:-2234}

exec ssh -i test/tmp/ssh-key -p "$SSHPORT" \
         -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
         root@127.0.0.1 "$@"
