#!/usr/bin/env bash
# Run a command inside the spun-up VM
set -Eeuo pipefail

SSHPORT=${SSHPORT:-2234}

ssh -i test/ssh-key -p "$SSHPORT" \
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    root@127.0.0.1 "$@"
